<?if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) {
	die();
}
?><?
CModule::IncludeModule("vampirus.yandexkassa");
IncludeModuleLangFile(__FILE__);

$psTitle       = GetMessage("VAMPIRUS.YANDEXKASSA_TITLE");
$psDescription = "";
$psDomain      = null;

$arPSCorrespondence = array(
	"SHOPID"                        => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_SHOPID"),
		"DESCR" => "",
		"SORT"  => -7,
	),
	"SCID"                          => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_SCID"),
		"DESCR" => "",
		"SORT"  => -6,
	),
	"PASSWORD"                      => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_PASSWORD"),
		"DESCR" => "",
		"SORT"  => -5,
	),
	"PAYMENT_ID"                    => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_ID"),
		"DESCR"   => "",
		"VALUE"   => "ID",
		"TYPE"    => "PAYMENT",
		"SORT"    => -4,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'PAYMENT',
			'PROVIDER_VALUE' => 'ID',
		),
	),
	"PAYMENT_NUMBER"                => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_NUMBER"),
		"DESCR"   => "",
		"VALUE"   => "ACCOUNT_NUMBER",
		"TYPE"    => "PAYMENT",
		"SORT"    => -4,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'PAYMENT',
			'PROVIDER_VALUE' => 'ACCOUNT_NUMBER',
		),
	),
	"ORDER_ID"                      => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_ORDER_ID"),
		"DESCR"   => "",
		"VALUE"   => "ID",
		"TYPE"    => "ORDER",
		"SORT"    => -4,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'ORDER',
			'PROVIDER_VALUE' => 'ID',
		),
	),
	"ORDER_NUMBER"                  => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_ORDER_NUMBER"),
		"DESCR"   => "",
		"VALUE"   => "ACCOUNT_NUMBER",
		"TYPE"    => "ORDER",
		"SORT"    => -3,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'ORDER',
			'PROVIDER_VALUE' => 'ACCOUNT_NUMBER',
		),
	),
	"SHOULD_PAY"                    => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_SHOULD_PAY"),
		"DESCR"   => "",
		"VALUE"   => "SHOULD_PAY",
		"TYPE"    => "ORDER",
		"SORT"    => -2,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'PAYMENT',
			'PROVIDER_VALUE' => 'SUM',
		),
	),
	"EMAIL"                         => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_EMAIL"),
		"DESCR"   => "",
		"VALUE"   => "EMAIL",
		"TYPE"    => "PROPERTY",
		"SORT"    => -1,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'USER',
			'PROVIDER_VALUE' => 'EMAIL',
		),
	),
	"FULL_NAME"                         => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_FULL_NAME"),
		"DESCR"   => "",
		"VALUE"   => "WORK_COMPANY",
		"TYPE"    => "PROPERTY",
		"SORT"    => -1,
		'DEFAULT' => array(
			'PROVIDER_KEY'   => 'USER',
			'PROVIDER_VALUE' => 'WORK_COMPANY',
		),
	),
	"INN"                         => array(
		"NAME"    => GetMessage("VAMPIRUS.YANDEXKASSA_INN"),
		"DESCR"   => GetMessage("VAMPIRUS.YANDEXKASSA_INN_DESC"),
		"SORT"    => -1,
	),
	"TAX_SYSTEM"                    => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM"),
		"DESCR" => "",
		"VALUE" => array(
			'1' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM_OSN")),
			'2' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM_USN6")),
			"3" => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM_USN15")),
			'4' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM_ENVD")),
			'5' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM_ESHD")),
			'6' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_SYSTEM_PSN")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -9,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_GROUP"),
	),
	"PRODUCT_NDS"                   => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_PRODUCT_NDS"),
		"DESCR" => "",
		"VALUE" => array(
			'0'                                  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_CATALOG")),
			CVampiRUSYandexKassaPayment::NO_VAT  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_1")),
			CVampiRUSYandexKassaPayment::VAT_0   => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_2")),
			CVampiRUSYandexKassaPayment::VAT_10  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_3")),
			CVampiRUSYandexKassaPayment::VAT_18  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_4")),
			CVampiRUSYandexKassaPayment::VAT_110 => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_5")),
			CVampiRUSYandexKassaPayment::VAT_118 => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_6")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -10,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_GROUP"),
	),
	"DELIVERY_NDS"                  => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_DELIVERY_NDS"),
		"DESCR" => "",
		"VALUE" => array(
			'0'                                  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_DELIVERY_OPTIONS")),
			CVampiRUSYandexKassaPayment::NO_VAT  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_1")),
			CVampiRUSYandexKassaPayment::VAT_0   => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_2")),
			CVampiRUSYandexKassaPayment::VAT_10  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_3")),
			CVampiRUSYandexKassaPayment::VAT_18  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_4")),
			CVampiRUSYandexKassaPayment::VAT_110 => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_5")),
			CVampiRUSYandexKassaPayment::VAT_118 => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_NDS_OPTIONS_6")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -12,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_GROUP"),
	),
	"PAYMENT_SUBJECT_TYPE"          => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_SUBJECT_TYPE"),
		"DESCR" => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_SUBJECT_TYPE_DESCR"),
		"VALUE" => array(
			'commodity'             => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_COMMODITY")),
			'excise'                => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_EXCISE")),
			'job'                   => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_JOB")),
			'service'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_SERVICE")),
			'gambling_bet'          => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_GAMBLING_BET")),
			'gambling_prize'        => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_GAMBLING_PRIZE")),
			'lottery'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_LOTTERY")),
			'lottery_prize'         => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_LOTTERY_PRIZE")),
			'intellectual_activity' => array('NAME' => GETMESSAGE("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_INTELLECTUAL_ACTIVITY")),
			'agent_commission'      => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_AGENT_COMMISSION")),
			'composite'             => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_COMPOSITE")),
			'payment'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_PAYMENT")),
			'another'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_ANOTHER")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -12,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_GROUP"),
	),
	"DELIVERY_PAYMENT_SUBJECT_TYPE" => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_DELIVERY_PAYMENT_SUBJECT_TYPE"),
		"DESCR" => "",
		"VALUE" => array(
			'commodity'             => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_COMMODITY")),
			'excise'                => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_EXCISE")),
			'job'                   => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_JOB")),
			'service'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_SERVICE")),
			'gambling_bet'          => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_GAMBLING_BET")),
			'gambling_prize'        => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_GAMBLING_PRIZE")),
			'lottery'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_LOTTERY")),
			'lottery_prize'         => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_LOTTERY_PRIZE")),
			'intellectual_activity' => array('NAME' => GETMESSAGE("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_INTELLECTUAL_ACTIVITY")),
			'agent_commission'      => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_AGENT_COMMISSION")),
			'composite'             => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_COMPOSITE")),
			'payment'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_PAYMENT")),
			'another'               => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_TYPE_OPTIONS_ANOTHER")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -12,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_GROUP"),
	),
	"PAYMENT_METHOD_TYPE"           => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_METHOD_TYPE"),
		"DESCR" => GetMessage("VAMPIRUS.YANDEXKASSA_PAYMENT_METHOD_TYPE_DESCR"),
		"VALUE" => array(
			'full_prepayment'    => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_FULL_PREPAYMENT")),
			'partial_prepayment' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_PARTIAL_PREPAYMENT")),
			'advance'            => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_ADVANCE")),
			'full_payment'       => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_FULL_PAYMENT")),
			'partial_payment'    => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_PARTIAL_PAYMENT")),
			'credit'             => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_CREDIT")),
			'credit_payment'     => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_METHOD_TYPE_OPTIONS_CREDIT_PAYMENT")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -12,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_TAX_GROUP"),
	),
	"CARD"                          => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_CARD"),
		"DESCR" => "",
		"VALUE" => array(
			'0'  => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_0")),
			'AC' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_AC")),
			"PC" => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_PC")),
			'GP' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_GP")),
			'AB' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_AB")),
			'MA' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_MA")),
			'PB' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_PB")),
			'WM' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_WM")),
			'QW' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_QW")),
			'MC' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_MC")),
			'SB' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_SB")),
			'MB' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_MB")),
			'CR' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_CR")),
			'EP' => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_CARD_EP")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => 7,
	),
	"MODE"                          => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_MODE"),
		"DESCR" => "",
		"VALUE" => array(
			"0" => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_MODE_WORK")),
			"1" => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_MODE_TEST")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => 8,
	),
	"HOLD_KEY"                      => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_KEY"),
		"DESCR" => "",
		"SORT"  => 2,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_GROUP"),
	),
	"HOLD_CERT"                     => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_CERT"),
		"DESCR" => "",
		"SORT"  => 1,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_GROUP"),
	),
	"HOLD"                          => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD"),
		"DESCR" => "",
		"VALUE" => array(
			"0" => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_OFF")),
			"1" => array('NAME' => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_ON")),
		),
		"TYPE"  => "SELECT",
		"SORT"  => -1,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_GROUP"),
	),
	"HOLD_CERT_PASS"                => array(
		"NAME"  => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_CERT_PASS"),
		"DESCR" => "",
		"SORT"  => 2,
		"GROUP" => GetMessage("VAMPIRUS.YANDEXKASSA_HOLD_GROUP"),
	),
);
