<?
$PERM["video"]["*"]="R";
$PERM["/"]["8"]="W";
$PERM["/"]["*"]="R";
$PERM["x"]["8"]="W";
$PERM["salons"]["8"]="W";
$PERM["contacts"]["8"]="W";
$PERM["returns"]["8"]="W";
$PERM["delivery"]["8"]="W";
$PERM["service"]["8"]="W";
$PERM["tmn"]["8"]="W";
$PERM["spb"]["8"]="W";
$PERM["rnd"]["8"]="W";
$PERM["payment"]["8"]="W";
$PERM["nn"]["8"]="W";
$PERM["legality"]["8"]="W";
$PERM["kzn"]["8"]="W";
$PERM["kgd"]["8"]="W";
$PERM["ekb"]["8"]="W";
$PERM["about"]["7"]="W";
$PERM["about"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["7"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["catalog"]["8"]="W";
$PERM["catalog"]["7"]="W";
?>